Added issue finish implementation.

diff --git a/git-issue b/git-issue
--- a/git-issue
+++ b/git-issue
@@ -17,22 +17,45 @@ fail() {
 	exit 1
 }
 
+startswith() { [ "$1" != "${1#$2}" ]; }
+git_local_branches() { git branch --no-color | sed 's/^[* ] //'; }
+git_current_branch() {
+	git branch --no-color | grep '^\* ' | grep -v 'no branch' | sed 's/^* //g'
+}
+
+git_issue_branch() {
+	echo "$(git_local_branches)" | grep "$1/"
+}
+
 cmd_start() {
+	echo "Starting $1"
 	SUMMARY=`$JIRA_CMD -a getFieldValue --field Summary --issue $1 2>/dev/null | sed -e '1d' | tr ' ' '_'`
 	test -n "$SUMMARY" || fail "Issue $1 Does Not Exist."
 	
-	BRANCH="$1/$SUMMARY"
+	local BRANCH="$1/$SUMMARY"
 	echo "creating branch $BRANCH"
 	git checkout -b $BRANCH development
 	
 	echo "updating issue $1"
 	$JIRA_CMD -a progressIssue --issue $1 --step "In Progress"
 	$JIRA_CMD -a updateIssue --issue $1 --assignee $JIRA_USER
-	
 }
 
 cmd_finish() {
-	echo "Finish $1"
+	if [ -n "$1" ]; then
+		local BRANCH=$(git_issue_branch "$1")
+	elif [ -z "$BRANCH" ]; then
+		local BRANCH=$(git_current_branch)
+	fi
+	
+	test -n "$BRANCH" || fail "Issue $1 is not currently being worked on."
+	echo "Finishing $BRANCH"
+	
+	git checkout development
+	git pull origin development 2>/dev/null
+	git merge --no-ff $BRANCH -m "Closing ${BRANCH%/*} #resolve"
+	git branch -d $BRANCH
+	git push origin development 2>/dev/null
 }
 
 main() {
@@ -44,10 +67,10 @@ main() {
 	JIRA_PASSWORD=$(git config jira.password || true)
 	JIRA_CLI=$(git config jira.cli || true)
 	
-	test -n $JIRA_SERVER || fail "Missing JIRA Server Config."
-	test -n $JIRA_USER || fail "Missing JIRA User Config."
-	test -n $JIRA_PASSWORD || fail "Missing JIRA Password Config."
-	test -n $JIRA_CLI || fail "Missing JIRA CLI Config."
+	test -n "$JIRA_SERVER" || fail "Missing JIRA Server Config."
+	test -n "$JIRA_USER" || fail "Missing JIRA User Config."
+	test -n "$JIRA_PASSWORD" || fail "Missing JIRA Password Config."
+	test -n "$JIRA_CLI" || fail "Missing JIRA CLI Config."
 	
 	JIRA_CMD="$JIRA_CLI --server $JIRA_SERVER --user $JIRA_USER --password $JIRA_PASSWORD"
 	
